apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
  - chart: ingress-nginx
    #helm:
     # valueFiles:
      #- $values/argo-cd/values.yaml
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.2
  #- ref: values
  #  repoURL: https://github.com/gopaljayanthi/argocd-aws.git
  #  targetRevision: master
  syncPolicy:
    automated: {}
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true