apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
  name: letsencrypt
spec:
  acme:
    email: gopal.jayanti@opsmx.io
    privateKeySecretRef:
      name: letsencrypt-tls
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx