ingress:
  enabled: true
  className: nginx
  annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: git.awsjpmc.opsmx.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gitea-tls
      hosts:
        - git.awsjpmc.opsmx.org

global:
  storageClass: gp2

postgresql-ha:
  pgpool:
    persistence:
      storageClass: gp2
  postgresql:
    persistence:
      storageClass: gp2


