server:
  ingress:
    enabled: true
    annotations: 
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      #cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    ingressClassName: "nginx"
    #hostname: "argocd.awsjpmc.opsmx.org"
    path: /
    pathType: Prefix
    tls: true
