prometheus:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - prometheus.awsjpmc.opsmx.org
    tls: true
